name: formkit
version: 0.1.0
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  context: ^0.1.2
  logr: ^0.2.0
  rxdart: ^0.27.7
  copy_with_extension_gen: ^5.0.4
  json_annotation: ^4.8.1
  setup_widget: ^0.1.0
  image_picker: ^1.0.4
  storage: ^0.1.0
  intl: ^0.19.0
  flutter_markdown: ^0.6.18+2
dev_dependencies:
  build_runner: ^2.4.6
  copy_with_extension: ^5.0.4
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
