/*
Package directive GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package directive

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v NameConfig) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{}, true
		case "Description":
			return []string{}, true
		case "On":
			return []string{}, true
		case "Args":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
