/*
Package field GENERATED BY gengo:enum 
DON'T EDIT THIS FILE
*/
package field

import (
	github_com_pkg_errors "github.com/pkg/errors"
)

var InvalidOperationTimeType = github_com_pkg_errors.New("invalid OperationTimeType")

func (OperationTimeType) EnumValues() []any {
	return []any{
		OPERATION_TIME_TYPE__ON_COMMITTED, OPERATION_TIME_TYPE__ON_CREATED,
	}
}
func ParseOperationTimeTypeLabelString(label string) (OperationTimeType, error) {
	switch label {
	case "提交时间":
		return OPERATION_TIME_TYPE__ON_COMMITTED, nil
	case "创建时间":
		return OPERATION_TIME_TYPE__ON_CREATED, nil

	default:
		return "", InvalidOperationTimeType
	}
}

func (v OperationTimeType) Label() string {
	switch v {
	case OPERATION_TIME_TYPE__ON_COMMITTED:
		return "提交时间"
	case OPERATION_TIME_TYPE__ON_CREATED:
		return "创建时间"

	default:
		return "UNKNOWN"
	}
}
