name: storage
version: 0.1.0
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  rxdart: ^0.27.7
  crypto: ^3.0.1
  uuid: ^3.0.7
  copy_with_extension: ^4.0.0
  json_annotation: ^4.8.1
dev_dependencies:
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^4.0.0
  test: ^1.24.3
  build_runner: ^2.4.6
