name: storage
version: 0.1.0
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  rxdart: ^0.27.7
  crypto: ^3.0.1
  uuid: ^4.2.1
  copy_with_extension: ^5.0.4
  json_annotation: ^4.8.1
  setup_widget: ^0.1.0
  logr: ^0.2.0
  context: ^0.1.2
dev_dependencies:
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.4
  test: ^1.24.3
  build_runner: ^2.4.6
