/*
Package collection GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package collection

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v StructField) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "FieldName":
			return []string{}, true
		case "Name":
			return []string{}, true
		case "Type":
			return []string{}, true
		case "Tag":
			return []string{}, true
		case "Optional":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
