name: worklistapp
version: 0.1.0
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  setup_widget: ^0.1.0
  flutter_inappwebview: ^6.0.0-beta.31
  roundtripper: ^0.2.0
  context: ^0.1.2
  logr: ^0.2.0
  path_provider: ^2.1.1
  storage: ^0.1.0
  rxdart: ^0.27.7
  copy_with_extension: ^5.0.4
  json_annotation: ^4.8.1
  crpe: ^0.1.0
  syncer: ^0.1.0
  uuid: ^4.2.1
  formkit: ^0.1.0
  url_launcher: ^6.2.2
  network_info_plus: ^4.1.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1
  open_file_plus: ^3.4.1
dev_dependencies:
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.4
  test: ^1.24.3
  build_runner: ^2.4.7
flutter:
  uses-material-design: true
