name: crpe
version: 0.1.0
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  json_annotation: ^4.8.1
  copy_with_extension_gen: ^5.0.4
  context: ^0.1.2
  logr: ^0.1.2
  rxdart: ^0.27.7
  roundtripper: ^0.1.2
  storage: ^0.1.0
dev_dependencies:
  build_runner: ^2.4.6
  copy_with_extension: ^5.0.4
  json_serializable: ^6.7.1
  test: ^1.24.9
