/*
Package worklist GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package worklist

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (v WorkList) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Schema":
			return []string{}, true
		case "Artifacts":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
